[build-system]
requires = ["scikit-build-core>=0.5", "pybind11>=2.10"]
build-backend = "scikit_build_core.build"

[project]
name = "minuit2"
version = "6.26.10"

[tool.scikit-build]
install.components = ["python"]
