name: deploy-book

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: se-for-sci
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install the kernel
        run: |
          python -m ipykernel install --user --name conda-env-se-for-sci-py

      - name: Build the book
        run: |
          jupyter-book build .

      - uses: actions/upload-artifact@v4
        with:
          name: jupyterbook
          path: _build/html/*

  build-pyodide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Pyodide output
        run: |
          pipx run nox -s pyodide

      - uses: actions/upload-artifact@v4
        with:
          name: jupyterlite
          path: _output/*

  build-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make slides
        run: npx @marp-team/marp-cli@latest --input-dir slides --output _output

      - uses: actions/upload-artifact@v4
        with:
          name: slides
          path: _output/*

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-book, build-pyodide, build-slides]
    if: github.event_name == 'push'
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/download-artifact@v4
        with:
          name: jupyterbook
          path: public

      - uses: actions/download-artifact@v4
        with:
          name: jupyterlite
          path: public/live

      - uses: actions/download-artifact@v4
        with:
          name: slides
          path: public/slides

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
